language: groovy

jdk:
  - openjdk8

after_success:
  - test $TRAVIS_BRANCH = "master" &&
    ./gradlew -Dgradle.publish.key=${GRADLE_PUBLISH_KEY} -Dgradle.publish.secret=${GRADLE_PUBLISH_SECRET} publishPlugins
